image: docker:git
services:
- docker:dind

build_fedora:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/jupyter:f24 ./fedora
    - docker push registry.gitlab.com/gbraad/jupyter:f24

